### ISSUE TITLE
Fix wego quality content attachments

### ISSUE THREAD

**Issue by NiekKleverkamp** [rickklaasboer/wego-overseer#278] opened 2023-10-02 11:51 UTC
Wego quality content currently doesn't work with attachments
![image](https://github.com/rickklaasboer/wego-overseer/assets/74187513/4768fb1e-3b65-466f-9dc5-fbc5ca709f15)

**Comment by rickklaasboer** [comment] 2023-10-03 18:33
Duplicate of https://github.com/rickklaasboer/wego-overseer/issues/93

**Closed** 2024-01-22 22:13 UTC
Labels: bug, good first issue
